version = 1

exclude_patterns = [
  "dist/**",
  "node_modules/**",
  "tmp/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["typescript"]
  environment = ["browser", "nodejs"]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "css"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true
